check-swagger:
	which swagger || (go get -u github.com/go-swagger/go-swagger/cmd/swagger)

swagger: check-swagger
	go mod vendor
	swagger generate spec -w ../ -o ../docs/swagger.yaml --scan-models

serve-swagger: swagger
	swagger serve -F=swagger ../docs/swagger.yaml